# Site settings
title: "Bangla Audiobook"
email: info@banglaaudiobook.in
description: Listen to the literary treasures of Bengali literature
copyright: Â© 2016-<script>document.write(new Date().getFullYear())</script> BanglaAudiobook.in - go listen!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://banglaaudiobook.in/" # the base hostname & protocol for your site
twitter_username: audiobookbangla
github_username:  banglaaudiobook
gravatar_url: http://www.gravatar.com/avatar/bb857653fcc6b02ec638ee4e64eaf872?s=120

googleplus_user: '100301306098556898455'
googleplus_hidden: false

#URL Details
host: 0.0.0.0

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: pygments
excerpt_separator: <!--more-->

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed